name: radio_app
description: A cross-platform internet radio player.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  socket_io_client: ^2.0.0
  flutter_webrtc: ^0.9.47
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
